name: verseSketch-dev
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - MongoDBSettings:ConnectionString=mongodb://mongo-db:27017
      - ASPNETCORE_URLS=http://+:80
      - JwtConfig:Key=super-duper-long-and-awesome-secret-key
    depends_on:
      - mongo-db
    networks:
      - app-dev-network


  mongo-db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-dev-network

networks:
  app-dev-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local