name: verseSketch-dev
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - PiperBaseString=http://piper-tts:5000/
      - MongoDBSettings:ConnectionString=mongodb://mongo-db:27017
      - ASPNETCORE_URLS=http://+:80
      - JwtConfig:Key=super-duper-long-and-awesome-secret-key
    depends_on:
     - mongo-db
     - piper-tts
    networks:
      - app-dev-network

  mongo-db:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-dev-network

  piper-tts:
    image: versesketch-piper-tts
    restart: unless-stopped
    networks:
      - app-dev-network

networks:
  app-dev-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local