name: verseSketch
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - PiperBaseString=http://piper-tts:5000/
      - MongoDBSettings:ConnectionString=mongodb://mongo-db:27017
      - ASPNETCORE_URLS=http://+:80
      - JwtConfig:Key=super-duper-long-and-awesome-secret-key
    depends_on:
      - mongo-db
      - piper-tts
    restart: unless-stopped
    networks:
      - app-network

  mongo-db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - app-network
      
  piper-tts:
    build:
      context: ./PiperSetup
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
