@VerseSketchBackend_HostAddress = http://localhost:5151

GET {{VerseSketchBackend_HostAddress}}/api/room/getRooms
Accept: application/json
###
GET {{VerseSketchBackend_HostAddress}}/api/room/getRoom
Accept: application/json
###
GET http://localhost:5151/api/rooms/validatePlayerNickname&nickname=penis&roomName=penis
Accept: application/json
###
POST http://localhost:5151/api/Room/CreateRoom
###
GET http://localhost:5151/openapi/v1.json
###
GET http://localhost:5151/api/validatePlayerNickname&nickname=penis&roomName=penis