@VerseSketchBackend_HostAddress = http://localhost:5151

GET {{VerseSketchBackend_HostAddress}}/api/room/getRooms
Accept: application/json
###
GET {{VerseSketchBackend_HostAddress}}/api/room/getRoom
Accept: application/json
###
GET {{VerseSketchBackend_HostAddress}}/api/room/getRoom?id=123hsudfh
Accept: application/json
